### ISSUE TITLE
Adding a new css rule to a selected element

### ISSUE THREAD

**Issue by potgieterdl** [matjaztrontelj/PinegrowCommunity#6]
currently to add a css rule is very cumbersome. you have to click add rules, then add new, then still assign to the poperty which either means clicking back and forth or adding the css without seeing the impact untill you added it to the element.

I suggest either add the css rule automatically if on a selected property and have a click add button for new rules to add it to selected element.

**Comment by matjaztrontelj** [comment]
Fixed in 1.03, available for download.

New workflow if element is selected: Add rule box has a Create & Assign button. If rule is class it will create it and assign the class to the selected element.

Also when you click on the rule for selected element in PROPS (blue button) it opens CSS tab with filter set to this rule.
